version: '3.8'
services:
  gestion-entreprises:
    build: .
    ports:
      - "3000:3000"
    environment:
      - MONGODB_URI=mongodb://mongo:27017/gestion-entreprises
    depends_on:
      - mongo

  mongo:
    image: mongo
    ports:
      - "27017:27017"